name: Frontend CI

on:
  push:
  pull_request:
    branches; 

jobs: 
  build-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.11
      uses: actions/setup-node@v4
      with: 
        node-version: 20.11
        cache-dependency-path: package-lock.json
        cache: 'npm'
    - run: npm install
    - run: npm run lint
    - run: npm run build